const YOU_WIN = "YOU_WIN";
const YOU_LOSE = "YOU_LOSE";

const STATUS_CHOOSE_WEAPON = "CHOOSE_WEAPON";
const STATUS_WAITING = "WAITING";
const STATUS_CANCELLED = "CANCELLED";
const STATUS_STARTED = "STARTED";
const STATUS_FINISHED = "FINISHED";

const STATUSES = [
  STATUS_CHOOSE_WEAPON,
  STATUS_WAITING,
  STATUS_CANCELLED,
  STATUS_STARTED,
  STATUS_FINISHED
];

module.exports = {
  YOU_WIN,
  YOU_LOSE,
  STATUS_CHOOSE_WEAPON,
  STATUS_WAITING,
  STATUS_CANCELLED,
  STATUS_STARTED,
  STATUS_FINISHED,
  STATUSES
};
